apiVersion: v1
kind: Service
metadata:
  name: kubernetes-octopus-underwater-app
  labels:
    app: octopus-underwater-app
spec:
  selector:
    app: octopus-underwater-app

  ports:
    - port: 28015
      targetPort: 80

  type: LoadBalancer
